mybatis:
  type-aliases-package: com.example.demo.model
  type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
spring:
  datasource:
    url: jdbc:mysql://localhost/chatroom?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  session:
    store-type: None
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

server:
  servlet:
    session:
      timeout: 3000
    context-path: /chatroom
  port: 8099
project:
  settings: null